# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk: oraclejdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

script: mvn clean package -DskipTests=true

cache:
  directories:
    - $HOME/.m2
# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      studentnstu97@mail.ru
    on_success: never # default: change
    on_failure: always # defa,ult: always
